spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hab_v2_db
    username: root
    password: Test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      max-file-size: 128MB
      max-request-size: 128MB

cloud:
  aws:
    credentials:
      access-key: AKIAZV5EVDGOMXH4WBVA
      secret-key: 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

    region:
      static: us-east-1
    stack:
      auto: false

application:
  bucket:
    name: playfulpursuitshub

